import { Inter } from 'next/font/google';
import { Rubik } from 'next/font/google';

import Footer from '@/components/footer/Footer';
import Providers from '@/components/provider/Providers';

import Header from './_header';
import './globals.css';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata = {
	title: 'Котейка',
	description: 'Generated by KlV',
};

export default function RootLayout({ children }) {
	return (
		<html lang='ru'>
			<body className={rubik.className}>
				<Providers>
					<Header />
					<main>{children}</main>
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
