import { Inter } from 'next/font/google';

import Footer from '@/components/footer/Footer';
import Providers from '@/components/provider/Providers';

import Header from './_header';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Котейка',
	description: 'Generated by KlV',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<Providers>
					<Header />
					<main className={inter.className}>{children}</main>
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
